# Created with package:mono_repo v1.2.0
language: dart

jobs:
  include:
    - stage: analyzer_and_format
      name: "SDK: stable - DIR: build_cli - TASKS: dartfmt -n --set-exit-if-changed ."
      script: ./tool/travis.sh dartfmt
      env: PKG="build_cli"
      dart: stable
    - stage: analyzer_and_format
      name: "SDK: dev - DIR: build_cli - TASKS: dartfmt -n --set-exit-if-changed ."
      script: ./tool/travis.sh dartfmt
      env: PKG="build_cli"
      dart: dev
    - stage: analyzer_and_format
      name: "SDK: stable - DIR: build_cli - TASKS: dartanalyzer --fatal-infos --fatal-warnings ."
      script: ./tool/travis.sh dartanalyzer
      env: PKG="build_cli"
      dart: stable
    - stage: analyzer_and_format
      name: "SDK: dev - DIR: build_cli - TASKS: dartanalyzer --fatal-infos --fatal-warnings ."
      script: ./tool/travis.sh dartanalyzer
      env: PKG="build_cli"
      dart: dev
    - stage: unit_test
      name: "SDK: stable - DIR: build_cli - TASKS: pub run test --run-skipped"
      script: ./tool/travis.sh test
      env: PKG="build_cli"
      dart: stable
    - stage: unit_test
      name: "SDK: dev - DIR: build_cli - TASKS: pub run test --run-skipped"
      script: ./tool/travis.sh test
      env: PKG="build_cli"
      dart: dev
    - stage: analyzer_and_format
      name: "SDK: dev - DIR: build_cli_annotations - TASKS: dartfmt -n --set-exit-if-changed ."
      script: ./tool/travis.sh dartfmt
      env: PKG="build_cli_annotations"
      dart: dev
    - stage: analyzer_and_format
      name: "SDK: dev - DIR: build_cli_annotations - TASKS: dartanalyzer --fatal-infos --fatal-warnings ."
      script: ./tool/travis.sh dartanalyzer
      env: PKG="build_cli_annotations"
      dart: dev

stages:
  - analyzer_and_format
  - unit_test

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.pub-cache"
