# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
targets:
  $default:
    builders:
      build_cli:
        generate_for:
          include:
          - example/**
          - test/src/*_example*

builders:
  build_cli:
    import: "package:build_cli/builder.dart"
    builder_factories: ["buildCli"]
    build_extensions: {".dart": [".build_cli.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
