# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      build_cli:
        generate_for:
          include:
          - example/**
          - test/src/*_example*
      source_gen|combining_builder:
        options:
          ignore_for_file:
          - lines_longer_than_80_chars

builders:
  checked:
    import: 'tool/builder.dart'
    builder_factories: ['defaultOverride']
    build_extensions: {".dart": [".overrides.dart"]}
    auto_apply: root_package
    build_to: source
    runs_before: ["build_cli"]
    defaults:
      generate_for:
        - test/src/peanut_example.dart

  build_cli:
    import: "package:build_cli/builder.dart"
    builder_factories: ["buildCli"]
    build_extensions: {".dart": [".build_cli.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
