# See with https://github.com/google/mono_repo.dart for details on this file
dart:
- 2.7.0
- dev

stages:
- analyzer_and_format:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-infos --fatal-warnings .
    dart: [dev]
  - group:
    - dartanalyzer: --fatal-warnings .
    dart: [2.7.0]
- unit_test:
  # Run the tests -- include the default-skipped presubmit tests
  - test: --run-skipped
