# See with https://github.com/google/mono_repo.dart for details on this file
dart:
- 2.12.0
- dev

stages:
- analyzer_and_format:
  - dartanalyzer: --fatal-infos --fatal-warnings .
  - dartfmt
- unit_test:
  - test: --run-skipped --reporter expanded
